apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: produce-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      run: produce-service
  template:
    metadata:
      labels:
        run: location-service
    spec:
      containers:
      - image: us.icr.io/openj9-demo/produce-service:latest
        name: produce-service
        ports:
        - containerPort: 8080
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:  
  name: produce-service-node-port
spec:
  selector:    
    run: produce-service
  type: NodePort
  ports:  
  - name: http
    port: 8080
    targetPort: 8080
    nodePort: 31416
    protocol: TCP